# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True, validators=[sites.models._simple_domain_name_validator], verbose_name='domain name')),
                ('name', models.CharField(max_length=50, verbose_name='display name')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'db_table': 'web_site',
                'ordering': ('domain',),
            },
            managers=[
                ('objects', sites.models.SiteManager()),
            ],
        ),
    ]
